spring:
  application:
    name: microservice-zull
server:
  port: 6010
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
zuul:
  routes:
    api-a.path: /api-a/**
    api-a.serviceId: microservice-consumer-movie-ribbon
    api-b.path: /api-b/**
    api-b.serviceId: microservice-consumer-movie-hystrix